# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# Using private gitlab runners, see: https://xiaomi.f.mioffice.cn/docs/dock4zQVbqzByBvzOot9vJ9ZY1c#

after_script:
  - echo "Git Tag is ${CI_COMMIT_TAG}"

stages:
  - build
  - test
  - release-binary
  - release-images
  - release-kind-images

build:
  stage: build
  script:
    - export GOPROXY="https://pkgs.d.xiaomi.net/artifactory/api/go/go-virtual"
    - export GOPRIVATE=*.xiaomi.com
    - echo "Build k8s binary"
    - make quick-verify
    - make
  tags:
    - k8s-build

test:
  stage: test
  script:
    - echo "Run k8s unit tests"
    - make test
  tags:
    - k8s-build

release-binary:
  stage: release-binary
  script:
    - echo "Build and Upload k8s binary"
    - make
    - bash build/upload-all-binaries.sh
  only:
    - tags
    - schedules
  tags:
    - k8s-build

release-images:
  stage: release-images
  script:
    - echo "Build and upload k8s images"
    - export KUBE_DOCKER_REGISTRY=cr.d.xiaomi.net/containercloud
    - export KUBE_BASE_IMAGE_REGISTRY=cr.d.xiaomi.net/containercloud
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" cr.d.xiaomi.net
    -  export KUBE_DOCKER_IMAGE_TAG=v1.21.3-mi-v1.21.3-dev-nightly-build
    - make quick-release-images
    - bash build/upload-all-images.sh
  only:
    - tags
    - schedules
  tags:
    - k8s-build

release-kind-images:
  stage: release-kind-images
  script:
    - echo "Build and upload kind images"
    - export KUBE_DOCKER_REGISTRY=cr.d.xiaomi.net/containercloud
    - export KUBE_BASE_IMAGE_REGISTRY=cr.d.xiaomi.net/containercloud
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" cr.d.xiaomi.net
    - export KUBE_DOCKER_IMAGE_TAG=v1.21.3-mi-v1.21.3-dev-nightly-build
    - export KIND_DOCKER_IMAGE=$KUBE_DOCKER_REGISTRY/kind-node:$KUBE_DOCKER_IMAGE_TAG
    - echo "Kind docker image':' $KIND_DOCKER_IMAGE"
    - kind build node-image --image=$KIND_DOCKER_IMAGE --kube-root=./
    - docker push $KIND_DOCKER_IMAGE
    - echo "Kind usage':' kind create cluster --image=$KIND_DOCKER_IMAGE"
  only:
    - tags
    - schedules
  tags:
    - k8s-build
